-- Expanded recipe catalog for Chill
-- Adds 180 more recipe ideas across many product categories.

insert into public.recipes (name, emoji, category, ingredients, keywords, diet, time_minutes, difficulty, source)
values
('Курица с рисом', '🍗', 'main', array['Курица','Рис','Лук','Морковь'], array['кур','куриц','рис','лук','морков'], array['glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Курица с гречкой', '🍗', 'main', array['Курица','Гречка','Лук','Морковь'], array['кур','куриц','греч','лук','морков'], array['glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Курица с овощами', '🍗', 'main', array['Курица','Кабачок','Перец','Морковь'], array['кур','куриц','кабач','перец','морков'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Курица с сливками', '🍗', 'main', array['Курица','Сливки','Сыр','Чеснок'], array['кур','куриц','сливк','сыр','чеснок'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Курица с грибами', '🍗', 'main', array['Курица','Грибы','Лук','Сметана'], array['кур','куриц','гриб','лук','сметан'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Курица с карри', '🍛', 'main', array['Курица','Карри','Рис','Сливки'], array['кур','куриц','карри','рис','сливк'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Курица с картофелем', '🍗', 'main', array['Курица','Картошка','Лук','Специи'], array['кур','куриц','картош','лук'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Курица с лапшой', '🍜', 'main', array['Курица','Лапша','Морковь','Лук'], array['кур','куриц','лапш','морков','лук'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Курица с томатами', '🍅', 'main', array['Курица','Помидоры','Чеснок','Базилик'], array['кур','куриц','помидор','томат','чеснок'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Курица с сыром', '🧀', 'main', array['Курица','Сыр','Сметана','Чеснок'], array['кур','куриц','сыр','сметан','чеснок'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Курица с фасолью', '🍲', 'main', array['Курица','Фасоль','Помидоры','Лук'], array['кур','куриц','фасол','помидор','лук'], array['glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Курица с кукурузой', '🌽', 'main', array['Курица','Кукуруза','Рис','Перец'], array['кур','куриц','кукуруз','рис','перец'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Курица с брокколи', '🥦', 'main', array['Курица','Брокколи','Сливки','Чеснок'], array['кур','куриц','броккол','сливк','чеснок'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Курица с соевым соусом', '🍚', 'main', array['Курица','Соевый соус','Рис','Чеснок'], array['кур','куриц','соев','рис','чеснок'], array['quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Курица с песто', '🍝', 'main', array['Курица','Песто','Паста','Сыр'], array['кур','куриц','песто','паст','сыр'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Курица с яблоками', '🍎', 'main', array['Курица','Яблоки','Лук','Специи'], array['кур','куриц','яблок','лук'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Курица с морковью', '🥕', 'main', array['Курица','Морковь','Лук','Сметана'], array['кур','куриц','морков','лук','сметан'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Курица с булгуром', '🍲', 'main', array['Курица','Булгур','Морковь','Лук'], array['кур','куриц','булгур','морков','лук'], array[], 35, 'easy', 'Chill expanded curated catalog'),
('Курица с шпинатом', '🥬', 'main', array['Курица','Шпинат','Сливки','Чеснок'], array['кур','куриц','шпинат','сливк','чеснок'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Курица с тыквой', '🎃', 'main', array['Курица','Тыква','Лук','Сливки'], array['кур','куриц','тыкв','лук','сливк'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Курица с капустой', '🥬', 'main', array['Курица','Капуста','Морковь','Лук'], array['кур','куриц','капуст','морков','лук'], array['glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Курица с нутом', '🍲', 'main', array['Курица','Нут','Помидоры','Лук'], array['кур','куриц','нут','помидор','лук'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Фарш с макаронами', '🍝', 'main', array['Фарш','Макароны','Лук','Томатная паста'], array['фарш','макарон','лук','томат'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Фарш с рисом', '🍚', 'main', array['Фарш','Рис','Морковь','Лук'], array['фарш','рис','морков','лук'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Котлеты домашние', '🥩', 'main', array['Фарш','Лук','Яйца','Хлеб'], array['фарш','лук','яйц','хлеб'], array[], 45, 'medium', 'Chill expanded curated catalog'),
('Тефтели в томатном соусе', '🍅', 'main', array['Фарш','Рис','Томатная паста','Лук'], array['фарш','рис','томат','лук'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Говядина с овощами', '🥩', 'main', array['Говядина','Перец','Морковь','Лук'], array['говяд','перец','морков','лук'], array['glutenfree'], 50, 'medium', 'Chill expanded curated catalog'),
('Свинина с картошкой', '🥩', 'main', array['Свинина','Картошка','Лук','Морковь'], array['свинин','картош','лук','морков'], array['glutenfree'], 55, 'medium', 'Chill expanded curated catalog'),
('Мясо с грибами', '🍄', 'main', array['Мясо','Грибы','Лук','Сметана'], array['мяс','гриб','лук','сметан'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Плов с мясом', '🍚', 'main', array['Мясо','Рис','Морковь','Лук'], array['мяс','рис','морков','лук'], array['glutenfree'], 60, 'medium', 'Chill expanded curated catalog'),
('Гуляш с гречкой', '🥘', 'main', array['Говядина','Гречка','Лук','Томатная паста'], array['говяд','греч','лук','томат'], array['glutenfree'], 55, 'medium', 'Chill expanded curated catalog'),
('Мясная запеканка', '🥧', 'main', array['Фарш','Картошка','Сыр','Лук'], array['фарш','картош','сыр','лук'], array['glutenfree'], 50, 'medium', 'Chill expanded curated catalog'),
('Перцы фаршированные', '🫑', 'main', array['Перец','Фарш','Рис','Морковь'], array['перец','фарш','рис','морков'], array['glutenfree'], 60, 'medium', 'Chill expanded curated catalog'),
('Ленивые голубцы', '🥬', 'main', array['Фарш','Капуста','Рис','Томатная паста'], array['фарш','капуст','рис','томат'], array['glutenfree'], 50, 'medium', 'Chill expanded curated catalog'),
('Мясо в сливочном соусе', '🥩', 'main', array['Мясо','Сливки','Лук','Чеснок'], array['мяс','сливк','лук','чеснок'], array['glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Свинина с капустой', '🥬', 'main', array['Свинина','Капуста','Морковь','Лук'], array['свинин','капуст','морков','лук'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Говядина с фасолью', '🍲', 'main', array['Говядина','Фасоль','Помидоры','Лук'], array['говяд','фасол','помидор','лук'], array['glutenfree'], 55, 'medium', 'Chill expanded curated catalog'),
('Фарш с кабачками', '🥒', 'main', array['Фарш','Кабачок','Помидоры','Лук'], array['фарш','кабач','помидор','лук'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Мясной суп', '🍲', 'main', array['Мясо','Картошка','Морковь','Лук'], array['мяс','картош','морков','лук'], array['glutenfree'], 60, 'medium', 'Chill expanded curated catalog'),
('Фарш с гречкой', '🍲', 'main', array['Фарш','Гречка','Лук','Морковь'], array['фарш','греч','лук','морков'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Бефстроганов', '🥩', 'main', array['Говядина','Сметана','Лук','Грибы'], array['говяд','сметан','лук','гриб'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Свинина с яблоками', '🍎', 'main', array['Свинина','Яблоки','Лук','Специи'], array['свинин','яблок','лук'], array['glutenfree'], 50, 'medium', 'Chill expanded curated catalog'),
('Мясо с булгуром', '🥘', 'main', array['Мясо','Булгур','Морковь','Лук'], array['мяс','булгур','морков','лук'], array[], 40, 'medium', 'Chill expanded curated catalog'),
('Фрикадельки с овощами', '🥘', 'main', array['Фарш','Морковь','Кабачок','Лук'], array['фарш','морков','кабач','лук'], array['glutenfree'], 35, 'easy', 'Chill expanded curated catalog'),
('Мясной соус к пасте', '🍝', 'main', array['Фарш','Паста','Помидоры','Чеснок'], array['фарш','паст','помидор','чеснок'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Стейк с овощами', '🥩', 'main', array['Говядина','Перец','Кабачок','Масло'], array['говяд','перец','кабач','масл'], array['glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Рыба с рисом', '🐟', 'seafood', array['Рыба','Рис','Лимон','Зелень'], array['рыб','рис','лимон','зелень'], array['glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Минтай с овощами', '🐟', 'seafood', array['Минтай','Морковь','Лук','Помидоры'], array['минтай','рыб','морков','лук','помидор'], array['glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Лосось с картошкой', '🐟', 'seafood', array['Лосось','Картошка','Лимон','Зелень'], array['лосос','рыб','картош','лимон'], array['glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Тунец с пастой', '🍝', 'seafood', array['Тунец','Паста','Помидоры','Сыр'], array['тунец','паст','помидор','сыр'], array['quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Рыбный суп', '🍲', 'seafood', array['Рыба','Картошка','Морковь','Лук'], array['рыб','картош','морков','лук'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Салат с тунцом', '🥗', 'seafood', array['Тунец','Яйца','Огурцы','Кукуруза'], array['тунец','яйц','огурц','кукуруз'], array['glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Рыба в сливках', '🐟', 'seafood', array['Рыба','Сливки','Сыр','Чеснок'], array['рыб','сливк','сыр','чеснок'], array['glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Рыбные котлеты', '🐟', 'seafood', array['Рыба','Яйца','Лук','Хлеб'], array['рыб','яйц','лук','хлеб'], array[], 40, 'medium', 'Chill expanded curated catalog'),
('Скумбрия с овощами', '🐟', 'seafood', array['Скумбрия','Перец','Лук','Помидоры'], array['скумбр','рыб','перец','лук','помидор'], array['glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Креветки с рисом', '🍤', 'seafood', array['Креветки','Рис','Чеснок','Лимон'], array['кревет','рис','чеснок','лимон'], array['glutenfree','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Креветки с пастой', '🍝', 'seafood', array['Креветки','Паста','Сливки','Сыр'], array['кревет','паст','сливк','сыр'], array['quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Рыба с гречкой', '🐟', 'seafood', array['Рыба','Гречка','Лук','Морковь'], array['рыб','греч','лук','морков'], array['glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Рыба с брокколи', '🥦', 'seafood', array['Рыба','Брокколи','Лимон','Масло'], array['рыб','броккол','лимон','масл'], array['glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Тунец с фасолью', '🥗', 'seafood', array['Тунец','Фасоль','Лук','Зелень'], array['тунец','фасол','лук','зелень'], array['glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Рыба в томатном соусе', '🍅', 'seafood', array['Рыба','Помидоры','Лук','Чеснок'], array['рыб','помидор','томат','лук','чеснок'], array['glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Лосось со шпинатом', '🥬', 'seafood', array['Лосось','Шпинат','Сливки','Чеснок'], array['лосос','шпинат','сливк','чеснок'], array['glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Рыба с кабачками', '🥒', 'seafood', array['Рыба','Кабачок','Помидоры','Лук'], array['рыб','кабач','помидор','лук'], array['glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Морской салат', '🥗', 'seafood', array['Креветки','Огурцы','Яйца','Йогурт'], array['кревет','огурц','яйц','йогурт'], array['glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Овощное рагу', '🥘', 'vegetarian', array['Картошка','Кабачок','Морковь','Перец'], array['картош','кабач','морков','перец'], array['vegetarian','glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Кабачки с сыром', '🥒', 'vegetarian', array['Кабачок','Сыр','Чеснок','Сметана'], array['кабач','сыр','чеснок','сметан'], array['vegetarian','glutenfree'], 30, 'easy', 'Chill expanded curated catalog'),
('Баклажаны с томатами', '🍆', 'vegetarian', array['Баклажан','Помидоры','Чеснок','Сыр'], array['баклаж','помидор','томат','чеснок','сыр'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Картошка с грибами', '🍄', 'vegetarian', array['Картошка','Грибы','Лук','Масло'], array['картош','гриб','лук','масл'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Овощи на сковороде', '🥦', 'vegetarian', array['Брокколи','Морковь','Перец','Кабачок'], array['броккол','морков','перец','кабач'], array['vegetarian','glutenfree','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Томатный суп', '🍅', 'vegetarian', array['Помидоры','Лук','Чеснок','Сливки'], array['помидор','томат','лук','чеснок','сливк'], array['vegetarian','glutenfree'], 30, 'easy', 'Chill expanded curated catalog'),
('Крем-суп из брокколи', '🥦', 'vegetarian', array['Брокколи','Картошка','Сливки','Лук'], array['броккол','картош','сливк','лук'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Морковные котлеты', '🥕', 'vegetarian', array['Морковь','Яйца','Мука','Сметана'], array['морков','яйц','мук','сметан'], array['vegetarian'], 30, 'easy', 'Chill expanded curated catalog'),
('Драники', '🥔', 'vegetarian', array['Картошка','Яйца','Мука','Лук'], array['картош','яйц','мук','лук'], array['vegetarian'], 30, 'easy', 'Chill expanded curated catalog'),
('Картошка по-деревенски', '🥔', 'vegetarian', array['Картошка','Масло','Чеснок','Специи'], array['картош','масл','чеснок'], array['vegetarian','glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Капуста с яйцом', '🥬', 'vegetarian', array['Капуста','Яйца','Лук','Масло'], array['капуст','яйц','лук','масл'], array['vegetarian','glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Фасоль с овощами', '🫘', 'vegetarian', array['Фасоль','Помидоры','Лук','Морковь'], array['фасол','помидор','лук','морков'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Нут с овощами', '🧆', 'vegetarian', array['Нут','Помидоры','Лук','Перец'], array['нут','помидор','лук','перец'], array['vegetarian','glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Хумус домашний', '🧆', 'vegetarian', array['Нут','Чеснок','Лимон','Масло'], array['нут','чеснок','лимон','масл'], array['vegetarian','glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Свекольный салат', '🥗', 'vegetarian', array['Свекла','Чеснок','Йогурт','Орехи'], array['свекл','чеснок','йогурт','орех'], array['vegetarian','glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Капустный салат', '🥗', 'vegetarian', array['Капуста','Морковь','Огурцы','Масло'], array['капуст','морков','огурц','масл'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Салат с фасолью', '🥗', 'vegetarian', array['Фасоль','Огурцы','Лук','Зелень'], array['фасол','огурц','лук','зелень'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Рататуй', '🍆', 'vegetarian', array['Баклажан','Кабачок','Помидоры','Перец'], array['баклаж','кабач','помидор','перец'], array['vegetarian','glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Овощная запеканка', '🥧', 'vegetarian', array['Кабачок','Картошка','Сыр','Яйца'], array['кабач','картош','сыр','яйц'], array['vegetarian','glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Грибной суп', '🍄', 'vegetarian', array['Грибы','Картошка','Лук','Сливки'], array['гриб','картош','лук','сливк'], array['vegetarian','glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Луковый суп', '🧅', 'vegetarian', array['Лук','Сыр','Хлеб','Масло'], array['лук','сыр','хлеб','масл'], array['vegetarian'], 35, 'medium', 'Chill expanded curated catalog'),
('Овощная паста', '🍝', 'vegetarian', array['Паста','Кабачок','Помидоры','Чеснок'], array['паст','кабач','помидор','чеснок'], array['vegetarian','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Брокколи с сыром', '🥦', 'vegetarian', array['Брокколи','Сыр','Сливки','Чеснок'], array['броккол','сыр','сливк','чеснок'], array['vegetarian','glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Тыквенный суп', '🎃', 'vegetarian', array['Тыква','Морковь','Лук','Сливки'], array['тыкв','морков','лук','сливк'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Тыква запечённая', '🎃', 'vegetarian', array['Тыква','Масло','Мёд','Орехи'], array['тыкв','масл','мед','мёд','орех'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Перец с сыром', '🫑', 'vegetarian', array['Перец','Сыр','Яйца','Зелень'], array['перец','сыр','яйц','зелень'], array['vegetarian','glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Картофельный салат', '🥔', 'vegetarian', array['Картошка','Огурцы','Яйца','Йогурт'], array['картош','огурц','яйц','йогурт'], array['vegetarian','glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Огуречный салат', '🥒', 'vegetarian', array['Огурцы','Йогурт','Чеснок','Зелень'], array['огурц','йогурт','чеснок','зелень'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Морковь по-домашнему', '🥕', 'vegetarian', array['Морковь','Чеснок','Масло','Специи'], array['морков','чеснок','масл'], array['vegetarian','glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Грибы в сметане', '🍄', 'vegetarian', array['Грибы','Сметана','Лук','Зелень'], array['гриб','сметан','лук','зелень'], array['vegetarian','glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Рисовая каша', '🍚', 'grains', array['Рис','Молоко','Сахар','Масло'], array['рис','молок','сахар','масл'], array['vegetarian','glutenfree'], 25, 'easy', 'Chill expanded curated catalog'),
('Гречневая каша', '🥣', 'grains', array['Гречка','Масло','Соль'], array['греч','масл'], array['vegetarian','glutenfree','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Булгур с овощами', '🍲', 'grains', array['Булгур','Перец','Морковь','Лук'], array['булгур','перец','морков','лук'], array['vegetarian','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Кускус с овощами', '🍲', 'grains', array['Кускус','Помидоры','Огурцы','Зелень'], array['кускус','помидор','огурц','зелень'], array['vegetarian','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Пшённая каша', '🥣', 'grains', array['Пшено','Молоко','Масло','Сахар'], array['пшен','молок','масл','сахар'], array['vegetarian','glutenfree'], 25, 'easy', 'Chill expanded curated catalog'),
('Перловка с грибами', '🍄', 'grains', array['Перловка','Грибы','Лук','Морковь'], array['перлов','гриб','лук','морков'], array['vegetarian'], 45, 'medium', 'Chill expanded curated catalog'),
('Паста с сыром', '🧀', 'grains', array['Паста','Сыр','Молоко','Масло'], array['паст','сыр','молок','масл'], array['vegetarian','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Паста с грибами', '🍝', 'grains', array['Паста','Грибы','Сливки','Лук'], array['паст','гриб','сливк','лук'], array['vegetarian','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Паста с брокколи', '🍝', 'grains', array['Паста','Брокколи','Сыр','Чеснок'], array['паст','броккол','сыр','чеснок'], array['vegetarian','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Паста с тунцом', '🍝', 'grains', array['Паста','Тунец','Помидоры','Лук'], array['паст','тунец','помидор','лук'], array['quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Макароны с яйцом', '🍝', 'grains', array['Макароны','Яйца','Сыр','Масло'], array['макарон','яйц','сыр','масл'], array['vegetarian','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Лапша с овощами', '🍜', 'grains', array['Лапша','Морковь','Перец','Соевый соус'], array['лапш','морков','перец','соев'], array['vegetarian','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Рис с яйцом', '🍚', 'grains', array['Рис','Яйца','Морковь','Соевый соус'], array['рис','яйц','морков','соев'], array['vegetarian','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Гречка с яйцом', '🥣', 'grains', array['Гречка','Яйца','Лук','Масло'], array['греч','яйц','лук','масл'], array['vegetarian','glutenfree','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Рис с фасолью', '🍚', 'grains', array['Рис','Фасоль','Помидоры','Лук'], array['рис','фасол','помидор','лук'], array['vegetarian','glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Каша с бананом', '🍌', 'grains', array['Овсянка','Банан','Молоко','Мёд'], array['овсян','банан','молок','мед','мёд'], array['vegetarian','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Овсянка с яблоком', '🍎', 'grains', array['Овсянка','Яблоки','Молоко','Корица'], array['овсян','яблок','молок','кориц'], array['vegetarian','quick'], 12, 'easy', 'Chill expanded curated catalog'),
('Рисовая запеканка', '🥧', 'grains', array['Рис','Яйца','Молоко','Сыр'], array['рис','яйц','молок','сыр'], array['vegetarian','glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Гречка с сыром', '🧀', 'grains', array['Гречка','Сыр','Яйца','Масло'], array['греч','сыр','яйц','масл'], array['vegetarian','glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Паста с овощами и сыром', '🍝', 'grains', array['Паста','Перец','Помидоры','Сыр'], array['паст','перец','помидор','сыр'], array['vegetarian','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Рис с кукурузой', '🌽', 'grains', array['Рис','Кукуруза','Морковь','Лук'], array['рис','кукуруз','морков','лук'], array['vegetarian','glutenfree','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Булгур с курицей', '🍲', 'grains', array['Булгур','Курица','Морковь','Лук'], array['булгур','кур','морков','лук'], array['quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Гречка с мясом', '🥘', 'grains', array['Гречка','Мясо','Лук','Морковь'], array['греч','мяс','лук','морков'], array['glutenfree'], 40, 'medium', 'Chill expanded curated catalog'),
('Лапша с курицей', '🍜', 'grains', array['Лапша','Курица','Морковь','Лук'], array['лапш','кур','морков','лук'], array['quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Макароны по-флотски', '🍝', 'grains', array['Макароны','Фарш','Лук','Масло'], array['макарон','фарш','лук','масл'], array['quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Омлет с сыром', '🧀', 'breakfast', array['Яйца','Сыр','Молоко','Масло'], array['яйц','сыр','молок','масл'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Омлет с овощами', '🥚', 'breakfast', array['Яйца','Перец','Помидоры','Зелень'], array['яйц','перец','помидор','зелень'], array['vegetarian','glutenfree','quick'], 12, 'easy', 'Chill expanded curated catalog'),
('Яйца с сыром', '🍳', 'breakfast', array['Яйца','Сыр','Масло','Зелень'], array['яйц','сыр','масл','зелень'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Творог с фруктами', '🍓', 'breakfast', array['Творог','Яблоки','Банан','Мёд'], array['творог','яблок','банан','мед','мёд'], array['vegetarian','glutenfree','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Йогурт с овсянкой', '🥣', 'breakfast', array['Йогурт','Овсянка','Банан','Орехи'], array['йогурт','овсян','банан','орех'], array['vegetarian','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Сэндвич с сыром', '🥪', 'breakfast', array['Хлеб','Сыр','Огурцы','Масло'], array['хлеб','сыр','огурц','масл'], array['vegetarian','quick'], 7, 'easy', 'Chill expanded curated catalog'),
('Сэндвич с курицей', '🥪', 'breakfast', array['Хлеб','Курица','Огурцы','Йогурт'], array['хлеб','кур','огурц','йогурт'], array['quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Тост с яйцом', '🍞', 'breakfast', array['Хлеб','Яйца','Сыр','Масло'], array['хлеб','яйц','сыр','масл'], array['vegetarian','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Лаваш с сыром', '🌯', 'breakfast', array['Лаваш','Сыр','Помидоры','Зелень'], array['лаваш','сыр','помидор','зелень'], array['vegetarian','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Лаваш с курицей', '🌯', 'breakfast', array['Лаваш','Курица','Огурцы','Йогурт'], array['лаваш','кур','огурц','йогурт'], array['quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Салат с яйцом', '🥗', 'breakfast', array['Яйца','Огурцы','Зелень','Йогурт'], array['яйц','огурц','зелень','йогурт'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Яблочные оладьи', '🥞', 'breakfast', array['Яблоки','Яйца','Мука','Сахар'], array['яблок','яйц','мук','сахар'], array['vegetarian'], 25, 'easy', 'Chill expanded curated catalog'),
('Банановые панкейки', '🥞', 'breakfast', array['Банан','Яйца','Мука','Молоко'], array['банан','яйц','мук','молок'], array['vegetarian'], 20, 'easy', 'Chill expanded curated catalog'),
('Творожная запеканка', '🥧', 'breakfast', array['Творог','Яйца','Сахар','Манная крупа'], array['творог','яйц','сахар','ман'], array['vegetarian'], 45, 'medium', 'Chill expanded curated catalog'),
('Запечённые яблоки', '🍎', 'breakfast', array['Яблоки','Мёд','Орехи','Корица'], array['яблок','мед','мёд','орех','кориц'], array['vegetarian','glutenfree'], 30, 'medium', 'Chill expanded curated catalog'),
('Банан с йогуртом', '🍌', 'breakfast', array['Банан','Йогурт','Орехи','Мёд'], array['банан','йогурт','орех','мед','мёд'], array['vegetarian','glutenfree','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Смузи с бананом', '🥤', 'breakfast', array['Банан','Молоко','Йогурт','Мёд'], array['банан','молок','йогурт','мед','мёд'], array['vegetarian','glutenfree','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Смузи с яблоком', '🥤', 'breakfast', array['Яблоки','Йогурт','Молоко','Корица'], array['яблок','йогурт','молок','кориц'], array['vegetarian','glutenfree','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Фруктовый йогурт', '🍓', 'breakfast', array['Йогурт','Яблоки','Банан','Орехи'], array['йогурт','яблок','банан','орех'], array['vegetarian','glutenfree','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Хлебцы с творогом', '🍞', 'breakfast', array['Хлебцы','Творог','Огурцы','Зелень'], array['хлебц','творог','огурц','зелень'], array['vegetarian','quick'], 7, 'easy', 'Chill expanded curated catalog'),
('Сырная тарелка', '🧀', 'breakfast', array['Сыр','Яблоки','Орехи','Хлеб'], array['сыр','яблок','орех','хлеб'], array['vegetarian','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Овощные палочки', '🥕', 'breakfast', array['Морковь','Огурцы','Йогурт','Чеснок'], array['морков','огурц','йогурт','чеснок'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Яичный салат для тостов', '🥚', 'breakfast', array['Яйца','Йогурт','Горчица','Хлеб'], array['яйц','йогурт','горчиц','хлеб'], array['vegetarian','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Гренки с сыром', '🍞', 'breakfast', array['Хлеб','Сыр','Яйца','Молоко'], array['хлеб','сыр','яйц','молок'], array['vegetarian','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Мини-пицца на хлебе', '🍕', 'breakfast', array['Хлеб','Сыр','Помидоры','Колбаса'], array['хлеб','сыр','помидор','колбас'], array['quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Картофельные лепёшки', '🥔', 'breakfast', array['Картошка','Яйца','Мука','Сыр'], array['картош','яйц','мук','сыр'], array['vegetarian','quick'], 30, 'medium', 'Chill expanded curated catalog'),
('Сырные шарики', '🧀', 'breakfast', array['Сыр','Яйца','Мука','Чеснок'], array['сыр','яйц','мук','чеснок'], array['vegetarian'], 25, 'easy', 'Chill expanded curated catalog'),
('Закуска из огурцов', '🥒', 'breakfast', array['Огурцы','Творог','Чеснок','Зелень'], array['огурц','творог','чеснок','зелень'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Помидоры с сыром', '🍅', 'breakfast', array['Помидоры','Сыр','Чеснок','Зелень'], array['помидор','сыр','чеснок','зелень'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Кукуруза с сыром', '🌽', 'breakfast', array['Кукуруза','Сыр','Йогурт','Зелень'], array['кукуруз','сыр','йогурт','зелень'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Салат из яблока и моркови', '🥗', 'breakfast', array['Яблоки','Морковь','Йогурт','Орехи'], array['яблок','морков','йогурт','орех'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Десерт из творога', '🍨', 'breakfast', array['Творог','Йогурт','Банан','Мёд'], array['творог','йогурт','банан','мед','мёд'], array['vegetarian','glutenfree','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Ягодный десерт', '🍓', 'breakfast', array['Ягоды','Йогурт','Мёд','Орехи'], array['ягод','йогурт','мед','мёд','орех'], array['vegetarian','glutenfree','quick'], 5, 'easy', 'Chill expanded curated catalog'),
('Запеканка с яблоками', '🥧', 'breakfast', array['Яблоки','Творог','Яйца','Сахар'], array['яблок','творог','яйц','сахар'], array['vegetarian'], 40, 'medium', 'Chill expanded curated catalog'),
('Овсяное печенье', '🍪', 'breakfast', array['Овсянка','Банан','Яйца','Мёд'], array['овсян','банан','яйц','мед','мёд'], array['vegetarian'], 25, 'easy', 'Chill expanded curated catalog'),
('Борщ домашний', '🍲', 'mixed', array['Свекла','Капуста','Картошка','Морковь'], array['свекл','капуст','картош','морков'], array['vegetarian','glutenfree'], 70, 'medium', 'Chill expanded curated catalog'),
('Щи с капустой', '🍲', 'mixed', array['Капуста','Картошка','Морковь','Лук'], array['капуст','картош','морков','лук'], array['vegetarian','glutenfree'], 55, 'medium', 'Chill expanded curated catalog'),
('Рассольник', '🍲', 'mixed', array['Огурцы','Перловка','Картошка','Морковь'], array['огурц','перлов','картош','морков'], array[], 60, 'medium', 'Chill expanded curated catalog'),
('Гороховый суп', '🍲', 'mixed', array['Горох','Картошка','Морковь','Лук'], array['горох','картош','морков','лук'], array['vegetarian','glutenfree'], 60, 'medium', 'Chill expanded curated catalog'),
('Сырный суп', '🧀', 'mixed', array['Сыр','Картошка','Морковь','Лук'], array['сыр','картош','морков','лук'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Куриный суп с лапшой', '🍜', 'mixed', array['Курица','Лапша','Морковь','Лук'], array['кур','лапш','морков','лук'], array[], 40, 'medium', 'Chill expanded curated catalog'),
('Фасолевый суп', '🍲', 'mixed', array['Фасоль','Картошка','Помидоры','Лук'], array['фасол','картош','помидор','лук'], array['vegetarian','glutenfree'], 50, 'medium', 'Chill expanded curated catalog'),
('Суп с фрикадельками', '🍲', 'mixed', array['Фарш','Картошка','Морковь','Лук'], array['фарш','картош','морков','лук'], array['glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Овощной бульон', '🥣', 'mixed', array['Морковь','Лук','Картошка','Зелень'], array['морков','лук','картош','зелень'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Чечевичный суп', '🍲', 'mixed', array['Чечевица','Морковь','Лук','Помидоры'], array['чечевиц','морков','лук','помидор'], array['vegetarian','glutenfree'], 45, 'medium', 'Chill expanded curated catalog'),
('Салат оливье простой', '🥗', 'mixed', array['Картошка','Морковь','Яйца','Огурцы'], array['картош','морков','яйц','огурц'], array['vegetarian','glutenfree','quick'], 30, 'easy', 'Chill expanded curated catalog'),
('Винегрет', '🥗', 'mixed', array['Свекла','Картошка','Морковь','Огурцы'], array['свекл','картош','морков','огурц'], array['vegetarian','glutenfree'], 35, 'medium', 'Chill expanded curated catalog'),
('Салат с крабовыми палочками', '🥗', 'mixed', array['Крабовые палочки','Кукуруза','Яйца','Огурцы'], array['краб','кукуруз','яйц','огурц'], array['quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Салат с кукурузой', '🥗', 'mixed', array['Кукуруза','Огурцы','Яйца','Йогурт'], array['кукуруз','огурц','яйц','йогурт'], array['vegetarian','glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Салат с сыром и помидорами', '🥗', 'mixed', array['Сыр','Помидоры','Огурцы','Зелень'], array['сыр','помидор','огурц','зелень'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Салат с гречкой', '🥗', 'mixed', array['Гречка','Огурцы','Помидоры','Сыр'], array['греч','огурц','помидор','сыр'], array['vegetarian','glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Салат с рисом', '🥗', 'mixed', array['Рис','Кукуруза','Огурцы','Яйца'], array['рис','кукуруз','огурц','яйц'], array['vegetarian','glutenfree','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Салат с яблоком и сыром', '🥗', 'mixed', array['Яблоки','Сыр','Орехи','Йогурт'], array['яблок','сыр','орех','йогурт'], array['vegetarian','glutenfree','quick'], 10, 'easy', 'Chill expanded curated catalog'),
('Салат с нутом', '🥗', 'mixed', array['Нут','Помидоры','Огурцы','Зелень'], array['нут','помидор','огурц','зелень'], array['vegetarian','glutenfree','quick'], 15, 'easy', 'Chill expanded curated catalog'),
('Салат с курицей и кукурузой', '🥗', 'mixed', array['Курица','Кукуруза','Огурцы','Йогурт'], array['кур','кукуруз','огурц','йогурт'], array['glutenfree','quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Пицца на лаваше', '🍕', 'mixed', array['Лаваш','Сыр','Помидоры','Курица'], array['лаваш','сыр','помидор','кур'], array['quick'], 20, 'easy', 'Chill expanded curated catalog'),
('Пицца с грибами', '🍕', 'mixed', array['Тесто','Грибы','Сыр','Помидоры'], array['тест','гриб','сыр','помидор'], array['vegetarian'], 35, 'medium', 'Chill expanded curated catalog'),
('Запеканка из макарон', '🥧', 'mixed', array['Макароны','Сыр','Яйца','Молоко'], array['макарон','сыр','яйц','молок'], array['vegetarian'], 35, 'medium', 'Chill expanded curated catalog'),
('Лазанья с фаршем', '🥘', 'mixed', array['Листы лазаньи','Фарш','Сыр','Томатная паста'], array['лазан','фарш','сыр','томат'], array[], 60, 'medium', 'Chill expanded curated catalog'),
('Буррито с фасолью', '🌯', 'mixed', array['Лаваш','Фасоль','Рис','Сыр'], array['лаваш','фасол','рис','сыр'], array['vegetarian','quick'], 25, 'easy', 'Chill expanded curated catalog'),
('Шаурма домашняя', '🌯', 'mixed', array['Лаваш','Курица','Огурцы','Помидоры'], array['лаваш','кур','огурц','помидор'], array['quick'], 20, 'easy', 'Chill expanded curated catalog')
on conflict (name) do update
set emoji = excluded.emoji,
    category = excluded.category,
    ingredients = excluded.ingredients,
    keywords = excluded.keywords,
    diet = excluded.diet,
    time_minutes = excluded.time_minutes,
    difficulty = excluded.difficulty,
    source = excluded.source,
    is_active = true,
    updated_at = now();
